group:
  - files:
      - source: class-timu-core.php
        dest: core/class-timu-core.php
      
      - source: assets/
        dest: core/assets/
        
    repos:
      - thisismyurl/thisismyurl-avif-support
      - thisismyurl/thisismyurl-svg-support
      - thisismyurl/thisismyurl-heic-support
      - thisismyurl/thisismyurl-webp-support
      - thisismyurl/thisismyurl-list-support